# --------------------------------------------------------------------------------------------------
# Config
# --------------------------------------------------------------------------------------------------
PROJECT_NAME := gbemu

MAJOR_VER = 0
MINOR_VER = 1
BUILD_NUM = 0

# --------------------------------------------------------------------------------------------------
# Additional Compile and link flags
# --------------------------------------------------------------------------------------------------
PREPROCESSOR_DEFINES += 


# --------------------------------------------------------------------------------------------------
# Directories
# --------------------------------------------------------------------------------------------------


# add all directories that contain a cpp file here
SRC_ROOT := ../src

SRC_DIRS := \
$(SRC_ROOT) 

# add additional include directories here
# -isystem is used for third-party libraries to avoid warnings
INC_DIRS += \
-I../src

# add additional library paths here
LIB_DIRS += 

# --------------------------------------------------------------------------------------------------
# Objects and sources
# --------------------------------------------------------------------------------------------------
CPP_SOURCES +=

EXTERNAL_OBJS +=

LIBS += 

# CppRules contains all the rules needed to build the project
include CppRules.mk

